2024-03-01 15:09:43.577973: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-01 15:09:43.627829: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-01 15:09:46.440288: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/ferrazzi/.conda/envs/gpu_venv_lates/lib/python3.8/site-packages/huggingface_hub/utils/_runtime.py:184: UserWarning: Pydantic is installed but cannot be imported. Please check your installation. `huggingface_hub` will default to not using Pydantic. Error message: '{e}'
  warnings.warn(
wandb: Currently logged in as: ferrazzipietro. Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/ferrazzi/.netrc
wandb: wandb version 0.16.3 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.16.0
wandb: Run data is saved locally in /extra/ferrazzi/llm/mistral_finetuning/wandb/run-20240301_150958-r65t7hn4
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run en.layer12024-03-01 15:09:58
wandb: ‚≠êÔ∏è View project at https://wandb.ai/ferrazzipietro/Qwen1.5-14B-Chat__adapters_en.layer1_4_torch.bfloat16_16_32_0.05_4_0.0002
wandb: üöÄ View run at https://wandb.ai/ferrazzipietro/Qwen1.5-14B-Chat__adapters_en.layer1_4_torch.bfloat16_16_32_0.05_4_0.0002/runs/r65t7hn4
wandb: üöÄ View run en.layer12024-03-01 15:09:58 at: https://wandb.ai/ferrazzipietro/Qwen1.5-14B-Chat__adapters_en.layer1_4_torch.bfloat16_16_32_0.05_4_0.0002/runs/r65t7hn4
wandb: Ô∏è‚ö° View job at https://wandb.ai/ferrazzipietro/Qwen1.5-14B-Chat__adapters_en.layer1_4_torch.bfloat16_16_32_0.05_4_0.0002/jobs/QXJ0aWZhY3RDb2xsZWN0aW9uOjE0NDQ3OTQ3Nw==/version_details/v0
wandb: Synced 6 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240301_150958-r65t7hn4/logs
Traceback (most recent call last):
  File "finetuning_iterative_qwen.py", line 220, in <module>
    main(ADAPTERS_CHECKPOINT,
  File "finetuning_iterative_qwen.py", line 70, in main
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/ferrazzi/.conda/envs/gpu_venv_lates/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 482, in from_pretrained
    resolved_config_file = cached_file(
  File "/home/ferrazzi/.conda/envs/gpu_venv_lates/lib/python3.8/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "/home/ferrazzi/.conda/envs/gpu_venv_lates/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ferrazzi/.conda/envs/gpu_venv_lates/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1201, in hf_hub_download
    os.makedirs(storage_folder, exist_ok=True)
  File "/home/ferrazzi/.conda/envs/gpu_venv_lates/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ferrazzi/.conda/envs/gpu_venv_lates/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ferrazzi/.conda/envs/gpu_venv_lates/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 2 more times]
  File "/home/ferrazzi/.conda/envs/gpu_venv_lates/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'
